In [833]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import calendar

Kompetisi

In [834]:
df_kompetisi = pd.read_csv('csv/data_kompetisi.csv', encoding='utf-8', encoding_errors='ignore', delimiter=";", dtype={'NIS': str})
df_kompetisi.head()

,NIS,Name,Major,Faculty,Student Year,Activity,Start Date,End Date,Period,Status,Level,Team Category,Criteria,Score
0,"1,06E+11",Aisha Safira Salsa H.P.,Management - Reguler Class,SBM,2023,LO Kreatif Ide Bisnis 2023,21/08/2023,29/11/2023,20231,Juara 3,External National,Team,Juara 3|External National|Team,15
1,"4,06E+11",Jessica Piter,Tourism - Culinary Business,SoT,2021,Cooking Competition Challenge 2023,01/01/2023,28/02/2023,20221,Juara 3,External International,Team,Juara 3|External International|Team,21
2,"7,06E+11",Nico Prasetyo,Information System,SIFT,2020,Apple Swift Student Challenge WWDC 2023,09/05/2023,09/05/2023,20222,Juara 1,External International,Individual,Juara 1|External International|Individual,21
3,"7,06E+11",Michael Eko Hartono Gunawan,Informatics,SIFT,2020,Artificial Guardian Angel (A.G.A) Hackathon Bali,02/09/2023,03/09/2023,20222,Juara 1,External International,Individual,Juara 1|External International|Individual,21
4,"1,06E+11",Albert Esli,Management - Reguler Class,SBM,2021,Techconnect Sandbox,30/05/2023,06/06/2023,20222,Juara 2,External National,Team,Juara 2|External National|Team,17

In [835]:
df_kompetisi = df_kompetisi[df_kompetisi['Score'] != 0]

In [836]:
df_kompetisi['Start Date'] = pd.to_datetime(df_kompetisi['Start Date'], errors='coerce', format='%d/%m/%Y')
df_kompetisi['End Date'] = pd.to_datetime(df_kompetisi['End Date'], errors='coerce', format='%d/%m/%Y')

df_kompetisi = df_kompetisi.dropna(subset=['Start Date', 'End Date'])

In [837]:
df_kompetisi.head()

,NIS,Name,Major,Faculty,Student Year,Activity,Start Date,End Date,Period,Status,Level,Team Category,Criteria,Score
0,"1,06E+11",Aisha Safira Salsa H.P.,Management - Reguler Class,SBM,2023,LO Kreatif Ide Bisnis 2023,2023-08-21,2023-11-29,20231,Juara 3,External National,Team,Juara 3|External National|Team,15
1,"4,06E+11",Jessica Piter,Tourism - Culinary Business,SoT,2021,Cooking Competition Challenge 2023,2023-01-01,2023-02-28,20221,Juara 3,External International,Team,Juara 3|External International|Team,21
2,"7,06E+11",Nico Prasetyo,Information System,SIFT,2020,Apple Swift Student Challenge WWDC 2023,2023-05-09,2023-05-09,20222,Juara 1,External International,Individual,Juara 1|External International|Individual,21
3,"7,06E+11",Michael Eko Hartono Gunawan,Informatics,SIFT,2020,Artificial Guardian Angel (A.G.A) Hackathon Bali,2023-09-02,2023-09-03,20222,Juara 1,External International,Individual,Juara 1|External International|Individual,21
4,"1,06E+11",Albert Esli,Management - Reguler Class,SBM,2021,Techconnect Sandbox,2023-05-30,2023-06-06,20222,Juara 2,External National,Team,Juara 2|External National|Team,17

In [838]:
start_range = '2023-01-01'
end_range = '2023-07-31'

# Filter the DataFrame where Start Date and End Date fall between January and July
df_kompetisi = df_kompetisi[(df_kompetisi['End Date'] >= start_range) & (df_kompetisi['End Date'] <= end_range)]

In [839]:
# levels = 'External Regional|External International'
# df = df[~df['Level'].str.contains(levels, na=False)]

In [840]:
df_kompetisi['Score'] = pd.to_numeric(df_kompetisi['Score'], errors='coerce')

In [841]:
df_kompetisi = df_kompetisi.drop(columns=['NIS', 'Student Year', 'Period'])

In [842]:
df_kompetisi = df_kompetisi.dropna()

In [843]:
df_kompetisi_teams = df_kompetisi[df_kompetisi['Team Category'] == 'Team'].drop_duplicates(subset=['Activity', 'Major', 'Criteria','Start Date', 'End Date'])
df_kompetisi_individuals = df_kompetisi[df_kompetisi['Team Category'] == 'Individual']

In [844]:
df_kompetisi_teams

,Name,Major,Faculty,Activity,Start Date,End Date,Status,Level,Team Category,Criteria,Score
1,Jessica Piter,Tourism - Culinary Business,SoT,Cooking Competition Challenge 2023,2023-01-01,2023-02-28,Juara 3,External International,Team,Juara 3|External International|Team,21
4,Albert Esli,Management - Reguler Class,SBM,Techconnect Sandbox,2023-05-30,2023-06-06,Juara 2,External National,Team,Juara 2|External National|Team,17
10,Cindy Laurent Siswanto,Accounting,SBM,SeaGames 2023 Cambodia,2023-05-10,2023-05-11,Juara 1,External International,Team,Juara 1|External International|Team,25
12,Alois Anthony Adhypranata,Tourism - Hotel and Tourism Business,SoT,Tourneio Amizade Surabaya (PUBG Mobile),2023-02-21,2023-02-21,Juara 3,External International,Team,Juara 3|External International|Team,21
22,Alleta Antjani Istanto,Management - Reguler Class,SBM,WIDYA MANDALA DEBATE COMPETITION,2023-02-18,2023-02-19,Juara 2,External National,Team,Juara 2|External National|Team,17
...,...,...,...,...,...,...,...,...,...,...,...
327,Celine Jessica W,Visual Communication Design,SCI,Respect Culture 2023 - Indonesia Series,2023-02-25,2023-02-25,Juara 1,External Regional,Team,Juara 1|External Regional|Team,12
342,Velanska Dixie Namira,Management - Reguler Class,SBM,Euphorade 2.0 Business Competition University,2023-02-13,2023-02-13,Juara 2,External National,Team,Juara 2|External National|Team,17
349,Aryo Bagaskoro,Communication Science,SoC,Short Movie Competition Dencofe 2031,2023-06-29,2023-06-29,Juara 2,External National,Team,Juara 2|External National|Team,17
361,Hanif Umron Riadi,Communication Science,SoC,Short Movie Competition Dencofe 2032,2023-01-16,2023-01-18,Juara 2,External National,Team,Juara 2|External National|Team,17
362,Citta Catherine Gozali,Communication Science,SoC,Short Movie Competition Dencofe 2033,2023-01-16,2023-03-18,Juara 2,External National,Team,Juara 2|External National|Team,17

In [845]:
df_kompetisi_combined = pd.concat([df_kompetisi_teams, df_kompetisi_individuals])
df_kompetisi_combined

,Name,Major,Faculty,Activity,Start Date,End Date,Status,Level,Team Category,Criteria,Score
1,Jessica Piter,Tourism - Culinary Business,SoT,Cooking Competition Challenge 2023,2023-01-01,2023-02-28,Juara 3,External International,Team,Juara 3|External International|Team,21
4,Albert Esli,Management - Reguler Class,SBM,Techconnect Sandbox,2023-05-30,2023-06-06,Juara 2,External National,Team,Juara 2|External National|Team,17
10,Cindy Laurent Siswanto,Accounting,SBM,SeaGames 2023 Cambodia,2023-05-10,2023-05-11,Juara 1,External International,Team,Juara 1|External International|Team,25
12,Alois Anthony Adhypranata,Tourism - Hotel and Tourism Business,SoT,Tourneio Amizade Surabaya (PUBG Mobile),2023-02-21,2023-02-21,Juara 3,External International,Team,Juara 3|External International|Team,21
22,Alleta Antjani Istanto,Management - Reguler Class,SBM,WIDYA MANDALA DEBATE COMPETITION,2023-02-18,2023-02-19,Juara 2,External National,Team,Juara 2|External National|Team,17
...,...,...,...,...,...,...,...,...,...,...,...
340,Aqilla Shahbani Mahazoya,Information System,SIFT,Piala GABSI Kota Malang 2023,2023-01-29,2023-01-29,Juara 3,External Regional,Individual,Juara 3|External Regional|Individual,6
341,Aileen Angelina Kurniawan,Visual Communication Design,SCI,Pirates of the socialite,2023-06-13,2023-06-13,Juara 2,External Regional,Individual,Juara 2|External Regional|Individual,7
353,Vivienne Valentin,Management - Reguler Class,SBM,Ruang Lomba Nasional tema Indonesia Berkarya,2023-04-22,2023-04-30,Juara 1,External National,Individual,Juara 1|External National|Individual,14
354,Vivienne Valentin,Management - Reguler Class,SBM,Ruang Lomba Nasional tema Indonesia Berkarya,2023-04-22,2023-04-30,Juara 3,External National,Individual,Juara 3|External National|Individual,11
358,Winda Christina Rosalim,Management - Reguler Class,SBM,Chess Competition dan PCUniverse 1.0,2023-04-23,2023-05-17,Juara 3,External Regional,Individual,Juara 3|External Regional|Individual,6

In [846]:
df_kompetisi_combined['Year'] = df_kompetisi_combined['End Date'].dt.year
df_kompetisi_combined['Month'] = df_kompetisi_combined['End Date'].dt.month.apply(lambda x: calendar.month_name[x])

In [847]:
df_kompetisi_scores = df_kompetisi_combined.groupby(['Major', 'Month', 'Year', 'Team Category', 'Status', 'Level'])['Score'].sum().reset_index()
df_kompetisi_scores

,Major,Month,Year,Team Category,Status,Level,Score
0,Accounting,February,2023,Team,Juara 1,External Regional,12
1,Accounting,January,2023,Individual,Juara 1,External National,14
2,Accounting,March,2023,Team,Juara 1,External National,18
3,Accounting,May,2023,Team,Juara 1,External International,25
4,Accounting,May,2023,Team,Juara 1,External National,36
...,...,...,...,...,...,...,...
115,Visual Communication Design,April,2023,Individual,Juara 3,External National,11
116,Visual Communication Design,February,2023,Team,Juara 1,External Regional,12
117,Visual Communication Design,January,2023,Individual,Juara 1,External Regional,8
118,Visual Communication Design,June,2023,Individual,Juara 2,External Regional,7
119,Visual Communication Design,March,2023,Team,Juara 2,External National,34

In [848]:
output_file_path_kompetisi = 'C:\\Users\\hansj\\OneDrive\\Documents\\Student Affairs\\Projects\\SIMKATMAWA\\output\\output_kompetisi.xlsx'
df_kompetisi_scores.to_excel(output_file_path_kompetisi, index=False)

Nonlomba

In [849]:
df_nonlomba = pd.read_csv('csv/data_nonlomba.csv', encoding='utf-8', encoding_errors='ignore', delimiter=";", dtype={'NIS': str})
df_nonlomba.head()

,NIS,Name,Major,Student Year,Activity,Start Date,End Date,Period,Description,Category,...,Total Participant,Point,Website,Certificate,Assignment Letter,Report,Documentation,Organizer,Criteria,Score
0,0506012110036,Aang Arif Amrullah,Communication Science,2021,LKMM & CRISTA XI UNISMA,2023-02-15,2023-02-15,20221,pemateri personal branding lkmm & crista XI un...,Rumpun Keterampilan Penunjang,...,150,10,https://instagram.com/lkmmcrista11?igshid=YmMy...,https://employee.uc.ac.id/index.php/file/get/s...,NaN,NaN,NaN,BEM FK UNISMA MALANG,Pembicara pada pelatihan/seminar/event berskal...,0
1,0506012110036,Aang Arif Amrullah,Communication Science,2021,Talkshow Hardiknas,2023-06-28,2023-06-28,20222,Pembicara Talkshow di event Hardiknas Universi...,Rumpun Keterampilan Penunjang,...,100,5,https://www.instagram.com/p/CrmvDj4r9j0/?igshi...,https://employee.uc.ac.id/index.php/file/get/s...,https://employee.uc.ac.id/index.php/file/get/s...,NaN,NaN,Universitas Ciputra,Narasumber / Pemateri Acara Seminar / Workshop...,0
2,0106012010066,Abdul Fitro Al Akbar,Management - Reguler Class,2020,The 10th International Conference on Entrepren...,2023-10-26,2023-10-27,20231,The 10th International Conference on Entrepren...,Rumpun Keterampilan Penunjang,...,500,10,https://icoen.org/,https://employee.uc.ac.id/index.php/file/get/s...,https://employee.uc.ac.id/index.php/file/get/s...,NaN,NaN,ICOEN,Narasumber / Pemateri Acara Seminar / Workshop...,0
3,0106012310392,Abelia Cahya Oktaviani,Management - Reguler Class,2023,The 10th International Conference on Entrepren...,2023-10-26,2023-10-27,20231,The 10th International Conference on Entrepren...,Rumpun Keterampilan Penunjang,...,500,10,https://icoen.org/,https://employee.uc.ac.id/index.php/file/get/s...,https://employee.uc.ac.id/index.php/file/get/s...,NaN,NaN,ICOEN,Narasumber / Pemateri Acara Seminar / Workshop...,0
4,0106012210318,Achmad Edas Athoillah Syah Putra,Management - Reguler Class,2022,The 10th International Conference on Entrepren...,2023-10-26,2023-10-27,20231,The 10th International Conference on Entrepren...,Rumpun Keterampilan Penunjang,...,500,10,https://icoen.org/,https://employee.uc.ac.id/index.php/file/get/s...,https://employee.uc.ac.id/index.php/file/get/s...,NaN,NaN,ICOEN,Narasumber / Pemateri Acara Seminar / Workshop...,0

In [850]:
df_nonlomba = df_nonlomba[df_nonlomba['Score'] != 0]

In [851]:
df_nonlomba.drop(columns=['Website', 'Certificate', 'Assignment Letter', 'Report', 'Documentation', 'Organizer'], inplace=True)

In [852]:
df_nonlomba = df_nonlomba[df_nonlomba['Status'] != 'Narasumber / Pemateri Acara Seminar / Workshop / Pemakalah']

In [853]:
df_nonlomba['Start Date'] = pd.to_datetime(df_nonlomba['Start Date'], errors='coerce')
df_nonlomba['End Date'] = pd.to_datetime(df_nonlomba['End Date'], errors='coerce')

df_nonlomba = df_nonlomba.dropna(subset=['Start Date', 'End Date'])

In [854]:
start_range = '2023-01-01'
end_range = '2023-07-31'

# Filter the DataFrame where Start Date and End Date fall between January and July
df_nonlomba = df_nonlomba[(df_nonlomba['End Date'] >= start_range) & (df_nonlomba['End Date'] <= end_range)]

In [855]:
df_nonlomba['Score'] = pd.to_numeric(df_nonlomba['Score'], errors='coerce')

In [856]:
df_nonlomba['Year'] = df_nonlomba['End Date'].dt.year
df_nonlomba['Month'] = df_nonlomba['End Date'].dt.month.apply(lambda x: calendar.month_name[x])

In [857]:
df_nonlomba_scores = df_nonlomba.groupby(['Major', 'Month', 'Year', 'Status', 'Level'])['Score'].sum().reset_index()
df_nonlomba_scores

,Major,Month,Year,Status,Level,Score
0,Accounting,January,2023,Penulis pertama buku ber-ISBN,External National,6
1,Accounting,May,2023,Penulis pertama pada jurnal internasional bere...,External National,5
2,Communication Science,July,2023,Penulis pertama pada jurnal internasional bere...,External International,5
3,Information System,February,2023,Pembicara pada pelatihan/seminar/event berskala,External National,4
4,Information System,February,2023,Penulis pertama pada jurnal internasional bere...,External International,5
5,Magister of Management,January,2023,Pemakalah dalam Conference/Seminar Ilmiah,External National,4
6,Magister of Management,January,2023,Pembicara pada pelatihan/seminar/event berskala,External National,8
7,Magister of Management,June,2023,Penulis pertama pada jurnal internasional bere...,External National,5
8,Management - Reguler Class,April,2023,Pembicara pada pelatihan/seminar/event berskala,External National,4
9,Management - Reguler Class,February,2023,Pemakalah dalam Conference/Seminar Ilmiah,External National,4
10,Management - Reguler Class,January,2023,Pembicara pada pelatihan/seminar/event berskala,External International,4
11,Medical,July,2023,Penulis pertama pada jurnal internasional bere...,External International,5
12,Medical,June,2023,Pembicara pada pelatihan/seminar/event berskala,External National,4
13,Medical,June,2023,Penulis pertama pada jurnal internasional bere...,External International,5
14,Medical,May,2023,Penulis pertama pada jurnal internasional bere...,External International,5
15,Psychology,February,2023,Penulis pertama buku ber-ISBN,External National,6
16,Tourism - Culinary Business,January,2023,Penulis pertama buku ber-ISBN,External National,6
17,Tourism - Hotel and Tourism Business,January,2023,Penulis pertama buku ber-ISBN,External National,6
18,Visual Communication Design,February,2023,Penulis pertama buku ber-ISBN,External National,12

In [858]:
output_file_path_nonlomba = 'C:\\Users\\hansj\\OneDrive\\Documents\\Student Affairs\\Projects\\SIMKATMAWA\\output\\output_nonlomba.xlsx'
df_nonlomba_scores.to_excel(output_file_path_nonlomba, index=False)