In [72]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import re
from collections import Counter

In [73]:
df = pd.read_csv('scraped_data.csv', encoding='utf-8', encoding_errors='ignore', delimiter=",")
df.head()

,alt,caption,childPosts/0/alt,childPosts/0/caption,childPosts/0/commentsCount,childPosts/0/dimensionsHeight,childPosts/0/dimensionsWidth,childPosts/0/displayUrl,childPosts/0/firstComment,childPosts/0/id,...,taggedUsers/17/is_verified,taggedUsers/17/profile_pic_url,taggedUsers/17/username,timestamp,type,url,videoDuration,videoPlayCount,videoUrl,videoViewCount
0,Photo shared by Info Lomba dan Beasiswa on Sep...,🏅𝐎𝐋𝐈𝐌𝐏𝐈𝐀𝐃𝐄 𝐀𝐊𝐀𝐃𝐄𝐌𝐈𝐊 𝐓𝐄𝐑𝐏𝐀𝐃𝐔 (𝐎𝐀𝐓)🏅\n\r\nUntuk ...,Photo shared by Info Lomba dan Beasiswa on Sep...,NaN,0.0,1080.0,1080.0,https://instagram.fyto1-1.fna.fbcdn.net/v/t51....,NaN,3.452709e+18,...,NaN,NaN,NaN,2024-09-08T17:04:20.000Z,Sidecar,https://www.instagram.com/p/C_qfPBIyfXH/,NaN,NaN,NaN,NaN
1,"Photo by INFO LOMBA MAHASISWA on September 10,...",Punya Mimpi Kuliah di Luar Negeri dan Balik Mo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2024-09-11T05:38:29.000Z,Image,https://www.instagram.com/p/C_w_IUPzHGt/,NaN,NaN,NaN,NaN
2,Photo by INFO EVENT LOMBA - BEASISWA on Septem...,🚀 𝐄𝐱𝐭𝐞𝐧𝐝𝐞𝐝 𝐑𝐞𝐠𝐢𝐬𝐭𝐫𝐚𝐭𝐢𝐨𝐧 𝐟𝐨𝐫 𝐗𝐩𝐞𝐫𝐢𝐞𝐧𝐜𝐞 2024 – 𝐃...,Photo by INFO EVENT LOMBA - BEASISWA on Septem...,NaN,0.0,1350.0,1080.0,https://instagram.fsyq9-1.fna.fbcdn.net/v/t51....,NaN,3.448791e+18,...,NaN,NaN,NaN,2024-09-03T07:19:03.000Z,Sidecar,https://www.instagram.com/p/C_ckR4byqZL/,NaN,NaN,NaN,NaN
3,Photo shared by Lomba Gratis | Event Gratis on...,"Hai, Youngpreneurs!👋🏻\n\nPunya ide bisnis kere...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2024-09-05T07:07:05.000Z,Image,https://www.instagram.com/p/C_hsgAHxJBQ/,NaN,NaN,NaN,NaN
4,Photo shared by Lomba Gratis | Event Gratis on...,PEKAN KOMPETISI SAINS PELAJAR INDONESIA\n\nDAF...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2024-09-12T06:28:27.000Z,Image,https://www.instagram.com/p/C_zppGhyxkf/,NaN,NaN,NaN,NaN

In [74]:
df = df[['alt', 'caption', 'timestamp', 'url']]
df.head()

,alt,caption,timestamp,url
0,Photo shared by Info Lomba dan Beasiswa on Sep...,🏅𝐎𝐋𝐈𝐌𝐏𝐈𝐀𝐃𝐄 𝐀𝐊𝐀𝐃𝐄𝐌𝐈𝐊 𝐓𝐄𝐑𝐏𝐀𝐃𝐔 (𝐎𝐀𝐓)🏅\n\r\nUntuk ...,2024-09-08T17:04:20.000Z,https://www.instagram.com/p/C_qfPBIyfXH/
1,"Photo by INFO LOMBA MAHASISWA on September 10,...",Punya Mimpi Kuliah di Luar Negeri dan Balik Mo...,2024-09-11T05:38:29.000Z,https://www.instagram.com/p/C_w_IUPzHGt/
2,Photo by INFO EVENT LOMBA - BEASISWA on Septem...,🚀 𝐄𝐱𝐭𝐞𝐧𝐝𝐞𝐝 𝐑𝐞𝐠𝐢𝐬𝐭𝐫𝐚𝐭𝐢𝐨𝐧 𝐟𝐨𝐫 𝐗𝐩𝐞𝐫𝐢𝐞𝐧𝐜𝐞 2024 – 𝐃...,2024-09-03T07:19:03.000Z,https://www.instagram.com/p/C_ckR4byqZL/
3,Photo shared by Lomba Gratis | Event Gratis on...,"Hai, Youngpreneurs!👋🏻\n\nPunya ide bisnis kere...",2024-09-05T07:07:05.000Z,https://www.instagram.com/p/C_hsgAHxJBQ/
4,Photo shared by Lomba Gratis | Event Gratis on...,PEKAN KOMPETISI SAINS PELAJAR INDONESIA\n\nDAF...,2024-09-12T06:28:27.000Z,https://www.instagram.com/p/C_zppGhyxkf/

In [75]:
df['timestamp'] = pd.to_datetime(df['timestamp']).dt.date

df.head()

,alt,caption,timestamp,url
0,Photo shared by Info Lomba dan Beasiswa on Sep...,🏅𝐎𝐋𝐈𝐌𝐏𝐈𝐀𝐃𝐄 𝐀𝐊𝐀𝐃𝐄𝐌𝐈𝐊 𝐓𝐄𝐑𝐏𝐀𝐃𝐔 (𝐎𝐀𝐓)🏅\n\r\nUntuk ...,2024-09-08,https://www.instagram.com/p/C_qfPBIyfXH/
1,"Photo by INFO LOMBA MAHASISWA on September 10,...",Punya Mimpi Kuliah di Luar Negeri dan Balik Mo...,2024-09-11,https://www.instagram.com/p/C_w_IUPzHGt/
2,Photo by INFO EVENT LOMBA - BEASISWA on Septem...,🚀 𝐄𝐱𝐭𝐞𝐧𝐝𝐞𝐝 𝐑𝐞𝐠𝐢𝐬𝐭𝐫𝐚𝐭𝐢𝐨𝐧 𝐟𝐨𝐫 𝐗𝐩𝐞𝐫𝐢𝐞𝐧𝐜𝐞 2024 – 𝐃...,2024-09-03,https://www.instagram.com/p/C_ckR4byqZL/
3,Photo shared by Lomba Gratis | Event Gratis on...,"Hai, Youngpreneurs!👋🏻\n\nPunya ide bisnis kere...",2024-09-05,https://www.instagram.com/p/C_hsgAHxJBQ/
4,Photo shared by Lomba Gratis | Event Gratis on...,PEKAN KOMPETISI SAINS PELAJAR INDONESIA\n\nDAF...,2024-09-12,https://www.instagram.com/p/C_zppGhyxkf/

In [76]:
keywords = ['mahasiswa', 'college', 'universitas', 'university', 'kompetisi', 'competition', 'nasional', 'lomba', 'olimpiade', 'olympiad']

df = df[df['caption'].str.contains('|'.join(keywords), case=False, na=False)]

df.head()

,alt,caption,timestamp,url
0,Photo shared by Info Lomba dan Beasiswa on Sep...,🏅𝐎𝐋𝐈𝐌𝐏𝐈𝐀𝐃𝐄 𝐀𝐊𝐀𝐃𝐄𝐌𝐈𝐊 𝐓𝐄𝐑𝐏𝐀𝐃𝐔 (𝐎𝐀𝐓)🏅\n\r\nUntuk ...,2024-09-08,https://www.instagram.com/p/C_qfPBIyfXH/
1,"Photo by INFO LOMBA MAHASISWA on September 10,...",Punya Mimpi Kuliah di Luar Negeri dan Balik Mo...,2024-09-11,https://www.instagram.com/p/C_w_IUPzHGt/
2,Photo by INFO EVENT LOMBA - BEASISWA on Septem...,🚀 𝐄𝐱𝐭𝐞𝐧𝐝𝐞𝐝 𝐑𝐞𝐠𝐢𝐬𝐭𝐫𝐚𝐭𝐢𝐨𝐧 𝐟𝐨𝐫 𝐗𝐩𝐞𝐫𝐢𝐞𝐧𝐜𝐞 2024 – 𝐃...,2024-09-03,https://www.instagram.com/p/C_ckR4byqZL/
3,Photo shared by Lomba Gratis | Event Gratis on...,"Hai, Youngpreneurs!👋🏻\n\nPunya ide bisnis kere...",2024-09-05,https://www.instagram.com/p/C_hsgAHxJBQ/
4,Photo shared by Lomba Gratis | Event Gratis on...,PEKAN KOMPETISI SAINS PELAJAR INDONESIA\n\nDAF...,2024-09-12,https://www.instagram.com/p/C_zppGhyxkf/

In [77]:
df.shape

(367, 4)

In [78]:
def extract_competition_name(caption):
    keywords_pattern = '|'.join([
        'mahasiswa', 'college', 'universitas', 'university',
        'kompetisi', 'competition', 'nasional', 'lomba',
        'olimpiade', 'olympiad'
    ])

    pattern = fr'(\w+(?:\s+\w+)*)\s+({keywords_pattern})\s+(\w+(\s+\w+)*)'
    
    match = re.search(pattern, caption, re.IGNORECASE)
    
    if match:
        preceding_words = match.group(1)
        keyword = match.group(2)
        competition_name = match.group(3)
        return {
            'preceding_words': preceding_words,
            'keyword': keyword,
            'competition_name': competition_name
        }
    return None

In [79]:
df['competition_name'] = df['caption'].apply(extract_competition_name)

df['competition_name'].head()

0    {'preceding_words': 'dan SMA Tingkat', 'keywor...
1    {'preceding_words': 'Disana akan ada puluhan',...
2                                                 None
3                                                 None
4    {'preceding_words': 'PEKAN', 'keyword': 'KOMPE...
Name: competition_name, dtype: object